services:
  ##################################
  # Node.js Insurance Service
  ##################################
  insurance-service:
    build:
      context: ../
      dockerfile: Dockerfile
    environment:
      # Using AWS RDS - no local MySQL needed
      DB_HOST: ${DB_HOST:-database-302.c7c2ciii0dcn.ap-southeast-1.rds.amazonaws.com}
      DB_PORT: ${DB_PORT:-3306}
      DB_USER: ${DB_USER:-admin}
      DB_PASSWORD: ${DB_PASSWORD:-c5fV9H4QGxTTfMynLPsT}
      DB_NAME: ${DB_NAME:-cs302DB}
      NODE_ENV: test
    ports:
      - "5200:5200"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:5200/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  ##################################
  # Pytest on Insurance Service
  ##################################
  insurance-pytest:
    build:
      context: ../
      dockerfile: ci/Dockerfile.test
    depends_on:
      insurance-service:
        condition: service_healthy
    environment:
      # AWS RDS connection for database setup
      DB_HOST: ${DB_HOST:-database-302.c7c2ciii0dcn.ap-southeast-1.rds.amazonaws.com}
      DB_PORT: ${DB_PORT:-3306}
      DB_USER: ${DB_USER:-admin}
      DB_PASSWORD: ${DB_PASSWORD:-c5fV9H4QGxTTfMynLPsT}
      DB_NAME: ${DB_NAME:-cs302DB}
      # Service URL for HTTP tests
      INSURANCE_SERVICE_URL: http://insurance-service:5200

