FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt ./
COPY ci/requirements.test.txt ./

RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir -r requirements.test.txt

COPY src/ ./src/
COPY tests/ ./tests/
COPY .env.example ./.env

ENV PYTHONPATH=/app/src

CMD ["python", "-m", "pytest", "tests/", "-v", "--tb=long", "-s", "--no-header"]
