services:
  ##################################
  # Pytest on Events-Stream Service
  ##################################
  events-stream-pytest:
    build:
      context: ../
      dockerfile: ci/Dockerfile.test
    depends_on:
      - rabbitmq
    environment:
      db_conn: mysql+mysqlconnector://root:root@mysql:3306