FROM python:3.12-slim
WORKDIR /usr/src/app

# Copy requirements and install dependencies
COPY requirements.txt ./
COPY ci/requirements.test.txt ./
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir -r requirements.test.txt

# Copy test files
COPY tests/ ./tests/

# Run pytest
CMD ["python", "-m", "pytest", "tests/", "-v"]