apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wearable
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/wearable.image-list: registry.gitlab.com/cs302-2025/g2-team5/services/wearable/main:latest
    argocd-image-updater.argoproj.io/wearable.update-strategy: digest
spec:
  project: default
  source:
    repoURL: https://gitlab.com/cs302-2025/g2-team5/k8s.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true