services:
  ##################################
  # Frontend Service (nginx)
  ##################################
  frontend:
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

  ##################################
  # Frontend Tests
  ##################################
  frontend-test:
    image: node:18-alpine
    depends_on:
      frontend:
        condition: service_healthy
    working_dir: /tests
    volumes:
      - ../:/tests
    environment:
      - FRONTEND_URL=http://frontend
    command: |
      sh -c "
        npm install -g html-validate &&
        html-validate *.html &&
        echo 'All tests passed!'
      "
